//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Performance
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Performance()
        {
            this.Players = new HashSet<Player>();
        }
    
        public int Id { get; set; }
        public double Avg_Rating { get; set; }
        public int Goals { get; set; }
        public int Assists { get; set; }
        public int Accurate_Pass { get; set; }
        public int Key_Pass { get; set; }
        public int Interception { get; set; }
        public int Successfully_Tackled { get; set; }
        public int Chance_Create { get; set; }
        public int Dribbles_Completed { get; set; }
        public int Saves { get; set; }
        public int Red_Cards { get; set; }
        public int Yellow_Cards { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Player> Players { get; set; }
    }
}
